name: church_of_christ
description: A new application for Church

version: 2.0.3+4

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ## Online
  dio: ^2.1.13
  flutter_mailer: ^0.4.1+2
  connectivity: ^0.4.3+7
  flutter_web_browser: ^0.11.0
  url_launcher: ^3.0.3
  image_picker:
  image_cropper: 1.0.2

  ## Icons
  font_awesome_flutter: ^8.4.0
  cupertino_icons: ^0.1.2
  icons_helper:
    git:
      url: git://github.com/sjmcdowall/icons_helper

  ## Firebase
  firebase_auth:
  google_sign_in:
  firebase_storage: ^3.0.6
  cloud_firestore: ^0.12.9+4

  ## Widgets
  add_2_calendar: ^1.3.0
  expand_widget: ^0.2.0+2
  flutter_local_notifications: ^0.8.2
  flutter_map: ^0.7.0+2
  flutter_markdown: ^0.2.0
  flutter_swiper: ^1.1.6
  material_search: ^0.2.8
  row_collection: ^0.2.3+1
  sliver_fab: ^1.0.0
  flutter_datetime_picker: 1.2.5
  flutter_slidable:
  pie_chart: ^1.2.0

  ##Tools
  flutter_i18n: ^0.6.4
  package_info: ^0.4.0+6
  share: ^0.6.2+1
  provider: ^3.1.0
  quick_actions: ^0.3.2+2
  shared_preferences: ^0.5.3+4
  system_setting: ^0.1.3
  qr_flutter: ^3.0.1
  date_format: ^1.0.6
  ##json_serializable: ^2.0.0
  geoflutterfire: ^2.0.3+5
  location: ^2.3.5
  google_maps_flutter: ^0.5.13
  flutter_google_places:
  flutter_money_formatter: ^0.8.3



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  #assets:

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

  assets:
    - assets/flutter_i18n/
    - assets/icons/
    - assets/images/place_holder.jpg
    - assets/images/place_holder_2.jpg
    - assets/images/place_holder_3.jpg
    - assets/images/
    - assets/data/currencies.json
    - assets/data/civilStatus.json
    - assets/data/gender.json